{{- $api_image := .Values.image.api_container_override | default (printf "%s/api:%s" .Values.image.repository .Chart.AppVersion) }}
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 5000
      protocol: TCP
      name: http
  selector:
    name: api-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      name: api-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: api-deployment
    spec:
      containers:
      - name: api-container
        image: "{{ $api_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        command: ["/usr/bin/tini"]
        args: ["--",
               "/usr/local/bin/docker-uid-gid-setup.sh",
               "/usr/local/bin/service_check_passthrough.sh",
               "-s",
               "api",
               "gunicorn",
               "--bind",
               "0:5000",
               "manage:app"]
        ports:
          - name: http
            protocol: TCP
            containerPort: 5000
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: upload-common-env
          - configMapRef:
              name: dashboards-env
          - configMapRef:
              name: opensearch-env
        env:
          - name: VIRTUAL_HOST
            value: "api.malcolm.local"
          - name: ARKIME_PORT
            value: "8005"
        livenessProbe:
          httpGet:
            path: /mapi/ping
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: api-var-local-catrust-volume
          - mountPath: /var/local/curlrc/secretmap
            name: api-opensearch-curlrc-secret-volume
      volumes:
        - name: api-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: api-opensearch-curlrc-secret-volume
          secret:
            secretName: opensearch-curlrc
