---
apiVersion: v1
kind: Service
metadata:
  name: valkey
spec:
  ports:
    - port: {{ .Values.valkey_env.ports.local.persistent }}
      protocol: TCP
      name: valkey
  selector:
    name: valkey-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-deployment
spec:
  selector:
    matchLabels:
      name: valkey-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: valkey-deployment
    spec:
      containers:
      {{ include "malcolm.valkey.container" (dict
        "root" $
        "name" "valkey-container"
        "mode" "main"
        "secretName" "valkey-env"
        "port" .Values.valkey_env.ports.local.persistent
        "portName" "valkey"
        "extraVolumeMounts" (list
          (dict "mountPath" "/data" "name" "valkey-volume" "subPath" "valkey")
        )
      ) | nindent 6 }}
      initContainers:
      {{ include "malcolm.dirinit.initContainer" (dict
           "root" $
           "name" "valkey-dirinit-container"
           "env" (list
             (dict "name" "PUSER_MKDIR" "value" "/data/config:valkey")
           )
           "volumeMounts" (list
             (dict "name" "valkey-volume" "mountPath" "/data/config")
           )
         ) | nindent 6 }}
      volumes:
        - name: var-local-catrust-volume
          configMap:
            name: {{ .Values.ca_trust_configmap_name | default "var-local-catrust" }}
        - name: valkey-volume
          persistentVolumeClaim:
            claimName: config-claim
