---
apiVersion: v1
kind: Service
metadata:
  name: valkey-cache
spec:
  ports:
    - port: {{ .Values.valkey_env.ports.local.cache }}
      protocol: TCP
      name: valkey
  selector:
    name: valkey-cache-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-cache-deployment
spec:
  selector:
    matchLabels:
      name: valkey-cache-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: valkey-cache-deployment
    spec:
      containers:
      {{ include "malcolm.valkey.container" (dict
          "root" $
          "name" "valkey-cache-container"
          "mode" "cache"
          "secretName" "valkey-env"
          "port" .Values.valkey_env.ports.local.cache
          "portName" "valkey-cache"
        ) | nindent 6 }}
      volumes:
        - name: var-local-catrust-volume
          configMap:
            name: {{ .Values.ca_trust_configmap_name | default "var-local-catrust" }}
