{{- $freq_image := .Values.image.freq_container_override | default (printf "%s/freq:%s" .Values.image.repository .Chart.AppVersion) }}
---
apiVersion: v1
kind: Service
metadata:
  name: freq
spec:
  ports:
    - port: 10004
      protocol: TCP
      name: http
  selector:
    name: freq-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freq-deployment
spec:
  selector:
    matchLabels:
      name: freq-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: freq-deployment
    spec:
      containers:
      - name: freq-container
        image: "{{ $freq_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        # TODO we should not be using root here
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        ports:
          - name: http
            protocol: TCP
            containerPort: 10004
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: lookup-common-env
        env:
          - name: VIRTUAL_HOST
            value: "freq.malcolm.local"
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/container_health.sh
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: freq-var-local-catrust-volume
      volumes:
        - name: freq-var-local-catrust-volume
          configMap:
            name: var-local-catrust
