{{- $dirinit_image := .Values.image.dirinit_container_override | default (printf "%s/dirinit:%s" .Values.image.repository .Chart.AppVersion) }}
{{- $pcap_monitor_image := .Values.image.pcap_monitor_container_override | default (printf "%s/pcap-monitor:%s" .Values.image.repository .Chart.AppVersion) }}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pcap-monitor
# spec:
#   ports:
#     - port: 30441
#       protocol: TCP
#       name: zmq
#   selector:
#     name: pcap-monitor-deployment

---
apiVersion: v1
data:
  AUTO_TAG: "true"
  PCAP_MONITOR_HOST: pcap-monitor
  PCAP_PIPELINE_IGNORE_PREEXISTING: "true"
  PCAP_PIPELINE_POLLING: "false"
  PCAP_PIPELINE_POLLING_ASSUME_CLOSED_SEC: "10"
  PCAP_PIPELINE_VERBOSITY: "-vv"
  EXTRA_TAGS: "{{ .Values.upload_common_env.extra_tags }}"
kind: ConfigMap
metadata:
  name: upload-live-env
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pcap-monitor-daemonset
spec:
  selector:
    matchLabels:
      name: pcap-monitor-daemonset
  template:
    metadata:
      labels:
        name: pcap-monitor-daemonset
    spec:
      containers:
      - name: pcap-monitor-container
        image: "{{ $pcap_monitor_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        env:
          - name: PCAP_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports:
          - name: zmq
            protocol: TCP
            containerPort: 30441
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          # I dont think we need these environment variables for 
          # storing already processed pcaps to ELASTIC in this use case.
          # - configMapRef:
          #     name: opensearch-env
          - configMapRef:
              name: upload-live-env
        livenessProbe:
          exec:
            command:
              - /usr/local/bin/container_health.sh
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - mountPath: /var/local/ca-trust/configmap
          name: pcap-monitor-var-local-catrust-volume
        - mountPath: /var/local/curlrc/secretmap
          name: pcap-monitor-opensearch-curlrc-secret-volume
        - mountPath: "/pcap"
          name: pcap-monitor-pcap-volume
        - mountPath: "/zeek"
          name: pcap-monitor-zeek-volume
      initContainers:
      - name: pcap-monitor-dirinit-container
        image: "{{ $dirinit_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: "/data/pcap:processed,upload"
        volumeMounts:
          - name: pcap-monitor-pcap-volume
            mountPath: "/data/pcap"
      volumes:
      - name: pcap-monitor-var-local-catrust-volume
        configMap:
          name: var-local-catrust
      - name: pcap-monitor-opensearch-curlrc-secret-volume
        secret:
          secretName: opensearch-curlrc
      - name: pcap-monitor-pcap-volume
        hostPath:
          path: "{{ .Values.arkime_live.pcap_hostpath }}"
          type: DirectoryOrCreate
      - name: pcap-monitor-zeek-volume
        hostPath:
          path: "{{ .Values.zeek_live.zeek_log_path }}"
          type: DirectoryOrCreate
        # TODO extract files should probably go to a shared PVC even while running at scale.
        # persistentVolumeClaim:
        #   claimName: zeek-claim

