{{- $dirinit_image := .Values.image.dirinit_container_override | default (printf "%s/dirinit:%s" .Values.image.repository .Chart.AppVersion) }}
{{- $pcap_monitor_image := .Values.image.pcap_monitor_container_override | default (printf "%s/pcap-monitor:%s" .Values.image.repository .Chart.AppVersion) }}
{{- $zeek_image := .Values.image.zeek_container_override | default (printf "%s/zeek:%s" .Values.image.repository .Chart.AppVersion) }}
{{- $suricata_image := .Values.image.suricata_container_override | default (printf "%s/suricata:%s" .Values.image.repository .Chart.AppVersion) }}
---
apiVersion: v1
data:
  ZEEK_AUTO_ANALYZE_PCAP_FILES: "true"
  PCAP_PROCESSED_DIRECTORY: "/pcap/arkime-live"
  ZEEK_UPLOAD_DIRECTORY: "/zeek/upload"
{{- if .Values.is_production }}
  {{- with .Values.zeek_offline.production }}
  ZEEK_AUTO_ANALYZE_PCAP_THREADS: "{{ .zeek_auto_analyze_pcap_threads }}"
  {{- end }}
{{- else }}
  {{- with .Values.zeek_offline.development }}
  ZEEK_AUTO_ANALYZE_PCAP_THREADS: "{{ .zeek_auto_analyze_pcap_threads }}"
  {{- end }}
{{- end }}
  ZEEK_PCAP_PROCESSOR: "true"
  ZEEK_ROTATED_PCAP: "false"
  # Set ZEEK_DISABLE_STATS to blank to generate stats.log and capture_loss.log
  ZEEK_DISABLE_STATS: "true"
  ZEEK_INTEL_REFRESH_CRON_EXPRESSION: "{{ .Values.zeek_offline.zeek_intel_refresh_cron_expression }}"
  ZEEK_INTEL_REFRESH_ON_STARTUP: "{{ .Values.zeek_offline.zeek_intel_refresh_on_startup }}"
kind: ConfigMap
metadata:
  name: zeek-pcap-offline-env

---
apiVersion: v1
data:
  .gitignore: |+
    *
    !.gitignore
kind: ConfigMap
metadata:
  name: suricata-configs
---
apiVersion: v1
data:
  AUTO_TAG: "true"
  PCAP_MONITOR_HOST: "localhost"
  PCAP_PIPELINE_IGNORE_PREEXISTING: "true"
  PCAP_PIPELINE_POLLING: "false"
  PCAP_PIPELINE_POLLING_ASSUME_CLOSED_SEC: "10"
  PCAP_PIPELINE_VERBOSITY: "-vv"
  EXTRA_TAGS: "{{ .Values.upload_common_env.extra_tags }}"
  OPENSEARCH_URL: ""
  OPENSEARCH_PRIMARY: ""
  OPENSEARCH_CREDS_CONFIG_FILE: ""
  OPENSEARCH_SSL_CERTIFICATE_VERIFICATION: ""
  # may need to be changed to /zeek/live/logs/current
  ZEEK_PATH: "/zeek"
  PCAP_PATH: "/pcap/arkime-live"
  WATCHER_UPLOAD: "false"
  WATCHER_PUBLISH: "true"
kind: ConfigMap
metadata:
  name: upload-pcap-offline-env

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pcap-processor-daemonset
spec:
  selector:
    matchLabels:
      name: pcap-processor-daemonset
  template:
    metadata:
      labels:
        name: pcap-processor-daemonset
    spec:
      containers:
      - name: pcap-monitor-container
        image: "{{ $pcap_monitor_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        env:
          - name: PCAP_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports:
          - name: zmq
            protocol: TCP
            containerPort: 30441
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: upload-pcap-offline-env
        # TODO fix livenessProbe later
        # livenessProbe:
        #   exec:
        #     command:
        #       - /usr/local/bin/container_health.sh
        #   initialDelaySeconds: 90
        #   periodSeconds: 30
        #   timeoutSeconds: 15
        #   successThreshold: 1
        #   failureThreshold: 10
        volumeMounts:
        - mountPath: /var/local/ca-trust/configmap
          name: var-local-catrust-volume
        - mountPath: "/pcap"
          name: pcap-volume
        - mountPath: "/zeek"
          name: zeek-volume
# Start of the ZEEK container
      - name: zeek-container
        image: "{{ $zeek_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: upload-pcap-offline-env
          - configMapRef:
              name: zeek-env
          - secretRef:
              name: zeek-secret-env
          - configMapRef:
              name: zeek-pcap-offline-env
        env:
          - name: PCAP_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        # livenessProbe intentionally omitted as per original comment
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: var-local-catrust-volume
          - mountPath: "/pcap"
            name: pcap-volume
          - mountPath: "/zeek/extract_files"
            name: extract-zeek-volume
            subPath: "extract_files"
          - mountPath: "/zeek/upload"
            name: zeek-volume
            subPath: "upload"
          - mountPath: "/opt/zeek/share/zeek/site/custom/configmap"
            name: zeek-custom-volume
          - mountPath: "/opt/zeek/share/zeek/site/intel-preseed/configmap"
            name: zeek-offline-intel-preseed-volume
          - mountPath: "/opt/zeek/share/zeek/site/intel"
            name: zeek-intel-volume
            subPath: "zeek/intel"
          - name: misp-config
            mountPath: "/opt/zeek/share/zeek/site/intel-preseed/MISP/.misp_input.txt"
            subPath: misp_input.txt
          - mountPath: /opt/zeek/share/zeek/site/custom
            name: zeek-intel-volume
            subPath: "zeek/custom"
          - mountPath: /opt/zeek/share/zeek/site/custom-global
            name: zeek-intel-volume
            subPath: "zeek/custom-global"
      - name: suricata-container
        image: "{{ $suricata_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        securityContext:
          # TODO we should not be using root here
          runAsGroup: 0
          runAsUser: 0
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: upload-common-env
          - configMapRef:
              name: suricata-env
          - configMapRef:
              name: suricata-offline-env
        env:
          - name: PCAP_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/container_health.sh
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: var-local-catrust-volume
          - mountPath: "/data/pcap"
            name: pcap-volume
          - mountPath: "/var/log/suricata"
            name: suricata-logs-volume
          - mountPath: "/opt/suricata/rules/configmap"
            name: suricata-custom-rules-volume
          - mountPath: "/opt/suricata/include-configs/configmap"
            name: suricata-custom-configs-volume
      initContainers:
      - name: dirinit-container
        image: "{{ $dirinit_image }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: >-
              /data/pcap:processed,upload;
              /data/config:zeek/intel/Mandiant,zeek/intel/MISP,zeek/intel/STIX;
              /data/zeek-logs:current,extract_files/preserved,extract_files/quarantine,live,processed,upload
        volumeMounts:
          - name: pcap-volume
            mountPath: "/data/pcap" 
          - name: zeek-intel-volume
            mountPath: "/data/config"
          - name: zeek-volume
            mountPath: "/data/zeek-logs"
      volumes:      
      - name: var-local-catrust-volume
        configMap:
          name: var-local-catrust
      - name: pcap-volume
        hostPath:
          path: "{{ .Values.arkime_live.pcap_hostpath }}"
          type: DirectoryOrCreate
      - name: misp-config
        secret:
          secretName: misp-api
      # Zeek volumes
      - name: zeek-volume
        hostPath:
          path: "{{ .Values.zeek_live.zeek_log_path }}"
          type: DirectoryOrCreate
      - name: zeek-custom-volume
        configMap:
          name: zeek-custom
      - name: zeek-offline-intel-preseed-volume
        configMap:
          name: zeek-intel-preseed
      - name: zeek-intel-volume
        persistentVolumeClaim:
          claimName: config-claim      
      - name: extract-zeek-volume
        persistentVolumeClaim:
          claimName: zeek-claim
      # Suricata stuff
      - name: suricata-logs-volume
        hostPath:
          path: "{{ .Values.suricata_live.suricata_log_path }}"
          type: DirectoryOrCreate
      - name: suricata-custom-rules-volume
        configMap:
          name: suricata-rules
      - name: suricata-custom-configs-volume
        configMap:
          name: suricata-configs