---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arkime-offline-env
data:
  ARKIME_AUTO_ANALYZE_PCAP_FILES: "{{ .Values.arkime_offline.auto_analyze_pcap_files }}"
  # Whether or not Arkime should analyze captured PCAP files captured
  #   by netsniff-ng/tcpdump (see PCAP_ENABLE_NETSNIFF and PCAP_ENABLE_TCPDUMP
  #   below). If ARKIME_LIVE_CAPTURE is true, this should be false: otherwise
  #   Arkime will see duplicate traffic.
  ARKIME_ROTATED_PCAP: "true"
  ARKIME_AUTO_ANALYZE_PCAP_THREADS: "{{ .Values.arkime_offline.auto_analyze_pcap_threads }}"
  ARKIME_EXPOSE_WISE_GUI: "{{ .Values.arkime_offline.expose_wise_gui }}"
  ARKIME_ALLOW_WISE_GUI_CONFIG: "{{ .Values.arkime_offline.allow_wise_gui_config }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arkime-env
data:
  ARKIME_SSL: "false"
  ARKIME_VIEWER_PORT: "8005"
  MANAGE_PCAP_FILES: "{{ .Values.arkime_env.manage_pcap_files }}"
  ARKIME_PCAP_LIBPCAP: "{{ .Values.arkime_env.pcap_libpcap }}"
  ARKIME_DEBUG_LEVEL: "{{ .Values.arkime_env.arkime_debug_level }}"
{{- if ne .Values.siem_env.malcolm_network_index_pattern "arkime_sessions3-*" }}
  # Always query all indices instead of trying to calculate which ones
  #   https://arkime.com/settings#queryAllIndices
  ARKIME_QUERY_ALL_INDICES: "true"
{{- else }}
  ARKIME_QUERY_ALL_INDICES: "false"
{{- end }}
{{- if and .Values.external_elasticsearch.enabled (not (empty .Values.external_elasticsearch.elastic_cert_name)) }}
  ARKIME_CERTFILE: "/usr/local/share/ca-certificates/elastic_ca.crt"
{{- end }}
{{- if .Values.is_production }}
  {{- with .Values.opensearch.production }}
  OPENSEARCH_MAX_SHARDS_PER_NODE: "{{ .cluster_max_shards_per_node }}"
  {{- end }}
  {{- with .Values.arkime_env.production }}
  ARKIME_FREESPACEG: "{{ .free_space_g }}"
  ARKIME_ROTATE_INDEX: "{{ .rotate_index }}"
  INDEX_MANAGEMENT_ENABLED: "{{ .index_management_enabled }}"
  INDEX_MANAGEMENT_OPTIMIZATION_PERIOD: "{{ .index_management_optimization_period }}"
  INDEX_MANAGEMENT_RETENTION_TIME: "{{ .index_management_retention_time }}"
  INDEX_MANAGEMENT_OLDER_SESSION_REPLICAS: "{{ .index_management_older_session_replicas }}"
  INDEX_MANAGEMENT_HISTORY_RETENTION_WEEKS: "{{ .index_management_history_retention_weeks }}"
  INDEX_MANAGEMENT_SEGMENTS: "{{ .index_management_segments }}"
  INDEX_MANAGEMENT_HOT_WARM_ENABLED: "{{ .index_management_hot_warm_enabled }}"
  ARKIME_SPI_DATA_MAX_INDICES: "{{ .spi_data_max_indices }}"
  {{- end }}
{{- else }}
  {{- with .Values.opensearch.development }}
  OPENSEARCH_MAX_SHARDS_PER_NODE: "{{ .cluster_max_shards_per_node }}"
  {{- end }}
  {{- with .Values.arkime_env.development }}
  ARKIME_FREESPACEG: "{{ .free_space_g }}"
  ARKIME_ROTATE_INDEX: "{{ .rotate_index }}"
  INDEX_MANAGEMENT_ENABLED: "{{ .index_management_enabled }}"
  INDEX_MANAGEMENT_OPTIMIZATION_PERIOD: "{{ .index_management_optimization_period }}"
  INDEX_MANAGEMENT_RETENTION_TIME: "{{ .index_management_retention_time }}"
  INDEX_MANAGEMENT_OLDER_SESSION_REPLICAS: "{{ .index_management_older_session_replicas }}"
  INDEX_MANAGEMENT_HISTORY_RETENTION_WEEKS: "{{ .index_management_history_retention_weeks }}"
  INDEX_MANAGEMENT_SEGMENTS: "{{ .index_management_segments }}"
  INDEX_MANAGEMENT_HOT_WARM_ENABLED: "{{ .index_management_hot_warm_enabled }}"
  ARKIME_SPI_DATA_MAX_INDICES: "{{ .spi_data_max_indices }}"
  {{- end }}
{{- end }}

{{- if .Values.arkime_live.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arkime-live-env
data:
  # Whether or Arkime should monitor live traffic on a local
  #   interface (PCAP_IFACE in pcap-capture.env specifies interface)
  ARKIME_LIVE_CAPTURE: "true"
  ARKIME_LIVE_NODE_HOST: "{{ .Values.arkime_live.arkime_live_node_host }}"
  ARKIME_MAGIC_MODE: "{{ .Values.arkime_live.magic_mode }}"
  ARKIME_PCAP_WRITE_METHOD: "{{ .Values.arkime_live.pcap_write_method }}"
  ARKIME_PCAP_READ_METHOD: "{{ .Values.arkime_live.pcap_read_method }}"
  ARKIME_PCAP_PROCESSOR: "false"
  # Indicates if the WISE service is on or off
  WISE: "off"
  {{- if .Values.is_production }}
    {{- with .Values.arkime_live.production }}
  ARKIME_COMPRESSION_TYPE: "{{ .arkime_compression_type }}"
  ARKIME_COMPRESSION_LEVEL: "{{ .arkime_compression_level }}"
  ARKIME_DB_BULK_SIZE: "{{ .arkime_db_bulk_size }}"
  ARKIME_MAX_PACKETS_IN_QUEUE: "{{ .arkime_max_packets_in_queue }}"
  ARKIME_PACKET_THREADS: "{{ .arkime_packet_threads }}"
  ARKIME_PCAP_WRITE_SIZE: "{{ .arkime_pcap_write_size }}"
  ARKIME_TPACKETV3_NUM_THREADS: "{{ .arkime_tpacketv3_num_threads }}"
  ARKIME_TPACKETV3_BLOCK_SIZE: "{{ .arkime_tpacketv3_block_size }}"
    {{- end }}
  {{- else }}
    {{- with .Values.arkime_live.development }}
  ARKIME_COMPRESSION_TYPE: "{{ .arkime_compression_type }}"
  ARKIME_COMPRESSION_LEVEL: "{{ .arkime_compression_level }}"
  ARKIME_DB_BULK_SIZE: "{{ .arkime_db_bulk_size }}"
  ARKIME_MAX_PACKETS_IN_QUEUE: "{{ .arkime_max_packets_in_queue }}"
  ARKIME_PACKET_THREADS: "{{ .arkime_packet_threads }}"
  ARKIME_PCAP_WRITE_SIZE: "{{ .arkime_pcap_write_size }}"
  ARKIME_TPACKETV3_NUM_THREADS: "{{ .arkime_tpacketv3_num_threads }}"
  ARKIME_TPACKETV3_BLOCK_SIZE: "{{ .arkime_tpacketv3_block_size }}"
    {{- end }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arkime-lua
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-custom-plugins
