{{- if and .Values.external_elasticsearch.enabled (not (empty .Values.external_elasticsearch.elastic_cert_name)) }}
{{- $elastic_secret := lookup "v1" "Secret" .Values.external_elasticsearch.namespace .Values.external_elasticsearch.elastic_cert_name }}
{{- $elastic_ca_body := "" }}
{{- if $elastic_secret }}
  {{- $elastic_ca_body = index $elastic_secret.data "ca.crt" | default "" }}
{{- end }}
{{- if $elastic_ca_body }}
# This generates a copy of the ElasticSearch CA certificate in the chart
# namespace.
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.external_elasticsearch.elastic_cert_name }}"
  annotations:
    # This needs to be in place before the firstrun.yaml Job runs
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  elastic_ca.crt: {{ $elastic_ca_body }}
{{- end }}
{{- end }}
