{{- if and .Values.external_elasticsearch.enabled .Values.external_elasticsearch.elastic_cert_name }}
{{- $elastic_ca := (lookup "v1" "Secret" .Values.external_elasticsearch.namespace .Values.external_elasticsearch.elastic_cert_name).data }}
{{- $elastic_ca_body := get $elastic_ca "ca.crt" | default "Invalid secret reference to elastic search" }}
# This generates a copy of the ElasticSearch CA certificate in the chart
# namespace.
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.external_elasticsearch.elastic_cert_name }}"
  annotations:
    # This needs to be in place before the firstrun.yaml Job runs
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  elastic_ca.crt: {{ $elastic_ca_body }}
{{- end }}
