---
apiVersion: v1
data:
  99_opensearch_output.conf: |
    output {
      if [event][kind] == "metric" {
        elasticsearch {
          id => "output_opensearch_malcolm_metrics"
          hosts => "${OPENSEARCH_URL:http://opensearch:9200}"
          ssl_certificate_verification => "false"
          manage_template => false
          document_id => "%{+YYMMdd}-%{[event][hash]}"
          ilm_rollover_alias => "{{ .Values.siem_env.logstash_override.rollover_alias_beats }}"
          ilm_pattern => "000001"
          ilm_policy => "{{ .Values.siem_env.logstash_override.ilm_beats_policy }}"
        }
      } else if [event][provider] == "suricata" {
        elasticsearch {
          id => "output_opensearch_malcolm_suricata"
          hosts => "${OPENSEARCH_URL:http://opensearch:9200}"
          ssl_certificate_verification => "false"
          manage_template => false
          document_id => "%{+YYMMdd}-%{[event][hash]}"
          ilm_rollover_alias => "{{ .Values.siem_env.logstash_override.rollover_alias_suricata }}"
          ilm_pattern => "000001"
          ilm_policy => "{{ .Values.siem_env.logstash_override.ilm_policy }}"
        }
      } else {
        elasticsearch {
          id => "output_opensearch_malcolm_zeek"
          hosts => "${OPENSEARCH_URL:http://opensearch:9200}"
          ssl_certificate_verification => "false"
          manage_template => false
          document_id => "%{+YYMMdd}-%{[event][hash]}"
          ilm_rollover_alias => "{{ .Values.siem_env.logstash_override.rollover_alias_zeek }}"
          ilm_pattern => "000001"
          ilm_policy => "{{ .Values.siem_env.logstash_override.ilm_policy }}"
        }
      }
    }
kind: ConfigMap
metadata:
  name: elastic-output-override

---
apiVersion: v1
data:
  malcolm_template.json: |
    {{- include "malcolm.ecstemplate" (dict 
        "index_patterns" (printf "%s-*" .Values.siem_env.logstash_override.rollover_alias_zeek) 
        "rollover_alias" .Values.siem_env.logstash_override.rollover_alias_zeek 
        "ilm_policy" .Values.siem_env.logstash_override.ilm_policy 
        "search_alias" .Values.siem_env.logstash_override.search_alias 
        "number_of_shards" .Values.siem_env.logstash_override.number_of_shards 
        "number_of_replicas" .Values.siem_env.logstash_override.number_of_replicas 
    ) | indent 4 }}

  malcolm_template_suricata.json: |
    {{- include "malcolm.ecstemplate" (dict 
        "index_patterns" (printf "%s-*" .Values.siem_env.logstash_override.rollover_alias_suricata) 
        "rollover_alias" .Values.siem_env.logstash_override.rollover_alias_suricata 
        "ilm_policy" .Values.siem_env.logstash_override.ilm_policy 
        "search_alias" .Values.siem_env.logstash_override.search_alias 
        "number_of_shards" .Values.siem_env.logstash_override.number_of_shards 
        "number_of_replicas" .Values.siem_env.logstash_override.number_of_replicas 
    ) | indent 4 }}

  malcolm_beats_template.json: |
    {{- include "malcolm.beatstemplate" (dict 
        "index_patterns" (printf "%s-*" .Values.siem_env.logstash_override.rollover_alias_beats) 
        "rollover_alias" .Values.siem_env.logstash_override.rollover_alias_beats 
        "ilm_policy" .Values.siem_env.logstash_override.ilm_beats_policy 
        "default_pipeline" .Values.siem_env.logstash_override.default_beats_pipeline 
    ) | indent 4 }}
kind: ConfigMap
metadata:
  name: malcolm-template-override
