{{- if .Values.siem_env.logstash_override.enabled }}
---
apiVersion: v1
data:
  99_opensearch_output.conf: |
    output {
      if [event][kind] == "metric" {
        elasticsearch {
          id => "output_opensearch_malcolm_metrics"
          hosts => "${OPENSEARCH_URL:http://opensearch:9200}"
          ssl_certificate_verification => "false"
          manage_template => false
          index => "%{[@metadata][malcolm_opensearch_index]}"
          document_id => "%{+YYMMdd}-%{[event][hash]}"
        }
      } else if [event][provider] == "suricata" {
        elasticsearch {
          id => "output_opensearch_malcolm_suricata"
          hosts => "${OPENSEARCH_URL:http://opensearch:9200}"
          ssl_certificate_verification => "false"
          manage_template => false
          document_id => "%{+YYMMdd}-%{[event][hash]}"
          ilm_rollover_alias => "{{ .Values.siem_env.logstash_override.rollover_alias_suricata }}"
          ilm_pattern => "000001"
          ilm_policy => "{{ .Values.siem_env.logstash_override.ilm_policy }}"
        }
      } else {
        elasticsearch {
          id => "output_opensearch_malcolm_zeek"
          hosts => "${OPENSEARCH_URL:http://opensearch:9200}"
          ssl_certificate_verification => "false"
          manage_template => false
          document_id => "%{+YYMMdd}-%{[event][hash]}"
          ilm_rollover_alias => "{{ .Values.siem_env.logstash_override.rollover_alias_zeek }}"
          ilm_pattern => "000001"
          ilm_policy => "{{ .Values.siem_env.logstash_override.ilm_policy }}"
        }
      }
    }
kind: ConfigMap
metadata:
  name: elastic-output-override

---
apiVersion: v1
data:
  malcolm_template.json: |
    {{- include "malcolm.ecstemplate" (dict "index_patterns" (printf "%s-*" .Values.siem_env.logstash_override.rollover_alias_zeek) "rollover_alias" .Values.siem_env.logstash_override.rollover_alias_zeek "ilm_policy" .Values.siem_env.logstash_override.ilm_policy "search_alias" .Values.siem_env.logstash_override.search_alias) | indent 4 }}

  malcolm_template_suricata.json: |
    {{- include "malcolm.ecstemplate" (dict "index_patterns" (printf "%s-*" .Values.siem_env.logstash_override.rollover_alias_suricata) "rollover_alias" .Values.siem_env.logstash_override.rollover_alias_suricata "ilm_policy" .Values.siem_env.logstash_override.ilm_policy "search_alias" .Values.siem_env.logstash_override.search_alias) | indent 4 }}
kind: ConfigMap
metadata:
  name: malcolm-template-override
{{- end }}
